# Generated by Django 5.1.7 on 2025-04-27 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="display_name",
            field=models.CharField(default="Smart_Coder_2", max_length=100),
        ),
    ]
