# Generated by Django 5.1.7 on 2025-04-24 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pairing", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="partner",
            name="partner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="partner",
                to="users.user",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="partner",
            unique_together={("enrollment", "partner")},
        ),
    ]
